name: entrancesat
channels:
  - fbriol
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - appdirs=1.4.4=py_0
  - argh=0.26.2=py37_0
  - argon2-cffi=20.1.0=py37he774522_1
  - astroid=2.4.2=py37_0
  - astropy=3.2.1=py37he774522_0
  - async_generator=1.10=py37h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - autopep8=1.5.4=py_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py37he774522_0
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2021.1.19=haa95532_0
  - cachetools=4.2.1=pyhd3eb1b0_0
  - certifi=2020.12.5=py37haa95532_0
  - cffi=1.14.4=py37hcd4344a_0
  - chardet=4.0.0=py37haa95532_1003
  - click=7.1.2=pyhd3eb1b0_0
  - click-plugins=1.1.1=py_0
  - cligj=0.7.1=py37haa95532_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=3.3.1=py37hcd4344a_0
  - curl=7.67.0=h2a8f88b_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.11.0=py37he774522_0
  - dask-core=2021.1.1=pyhd3eb1b0_0
  - decorator=4.4.2=pyhd3eb1b0_0
  - defusedxml=0.6.0=py_0
  - deprecated=1.2.11=pyhd3eb1b0_0
  - descartes=1.1.0=py_4
  - diff-match-patch=20200713=py_0
  - docutils=0.16=py37_1
  - earthengine-api=0.1.236=pyh9f0ad1d_0
  - entrypoints=0.3=py37_0
  - expat=2.2.10=h33f27b4_2
  - fes=2.9.1=py37_0
  - fiona=1.8.4=py37h22081e2_0
  - flake8=3.8.4=py_0
  - freetype=2.10.4=hd328e21_0
  - freexl=1.0.6=h2bbff1b_0
  - future=0.18.2=py37_1
  - gdal=2.3.3=py37hdf43c64_0
  - geopandas=0.4.1=py_0
  - geos=3.7.1=h33f27b4_0
  - glob2=0.7=pyhd3eb1b0_0
  - google-api-core=1.22.2=py37h21ff451_0
  - google-api-python-client=1.12.8=pyhd3deb0d_0
  - google-auth=1.21.3=py_0
  - google-auth-httplib2=0.0.4=pyh9f0ad1d_0
  - google-cloud-core=1.5.0=pyhd3eb1b0_0
  - google-cloud-storage=1.35.0=pyhd3eb1b0_0
  - google-crc32c=1.1.1=py37h2bbff1b_0
  - google-resumable-media=1.2.0=pyhd3eb1b0_1
  - googleapis-common-protos=1.52.0=py37h21ff451_0
  - hdf4=4.2.13=h712560f_2
  - hdf5=1.10.4=h7ebc959_0
  - httplib2=0.18.1=pyh9f0ad1d_0
  - hypothesis=6.1.1=pyhd3eb1b0_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - imageio=2.9.0=py_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2020.2=254
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.20.0=py37hd4e2768_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.7.0=pyhd3eb1b0_0
  - jedi=0.17.2=py37haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kealib=1.4.7=h07cbb95_6
  - keyring=22.0.1=py37haa95532_0
  - kiwisolver=1.3.1=py37hd77b12b_0
  - krb5=1.16.4=hc04afaa_0
  - lazy-object-proxy=1.4.3=py37h2bbff1b_2
  - libboost=1.67.0=hd9e427e_4
  - libcrc32c=1.1.1=ha925a31_2
  - libcurl=7.67.0=h2a8f88b_0
  - libgdal=2.3.3=h10f50ba_0
  - libiconv=1.15=h1df5818_7
  - libkml=1.3.0=he5f2a48_4
  - libnetcdf=4.6.1=h411e497_2
  - libpng=1.6.37=h2a8f88b_0
  - libpq=11.2=h3235a2c_0
  - libprotobuf=3.14.0=h23ce68f_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h33f27b4_0
  - libspatialite=4.3.0a=hc36aec2_19
  - libssh2=1.9.0=h7a1dbc1_1
  - libtiff=4.1.0=h56a325e_1
  - libxml2=2.9.10=hb89e7f3_3
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mapclassify=2.2.0=py_0
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.0.3=py37hc8f65d3_0
  - matplotlib-base=3.3.2=py37hba9282a_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.2.0=py37h45dec08_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py37h2bbff1b_2
  - munch=2.5.0=py_0
  - mypy_extensions=0.4.3=py37_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.2.0=py37haa95532_0
  - numpy=1.16.3=py37h19fb1c0_0
  - numpy-base=1.16.3=py37hc3f5095_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py37_0
  - openssl=1.1.1i=h2bbff1b_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=0.24.2=py37ha925a31_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py37haa95532_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - pathspec=0.7.0=py_0
  - pcre=8.44=ha925a31_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=6.2.1=py37hdc69c19_0
  - pip=20.3.3=py37haa95532_0
  - pluggy=0.13.1=py37_0
  - proj4=5.2.0=ha925a31_1
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - protobuf=3.14.0=py37hd77b12b_1
  - psutil=5.8.0=py37h2bbff1b_1
  - psycopg2=2.8.4=py37h7a1dbc1_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.10.0=pyhd3eb1b0_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.6.0=py_0
  - pycparser=2.20=py_2
  - pydocstyle=5.1.1=py_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.7.4=pyhd3eb1b0_0
  - pylint=2.6.0=py37_0
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py37h62dcd97_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyproj=1.9.6=py37h6782396_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.17.3=py37he774522_0
  - pysocks=1.7.1=py37_1
  - pytest=6.2.2=py37haa95532_2
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.8.0=pyhd3eb1b0_0
  - pytest-astropy-header=0.1.2=pyhd3eb1b0_0
  - pytest-doctestplus=0.9.0=pyhd3eb1b0_0
  - pytest-openfiles=0.5.0=pyhd3eb1b0_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.9=h60c2a47_0
  - python-dateutil=2.8.1=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py37he774522_2
  - pywin32=227=py37he774522_1
  - pywin32-ctypes=0.2.0=py37_1001
  - pywinpty=0.5.7=py37_0
  - pyyaml=5.4.1=py37h2bbff1b_1
  - pyzmq=20.0.0=py37hd77b12b_1
  - qdarkstyle=2.8.1=py_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.1=py_0
  - qtconsole=5.0.2=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - regex=2020.11.13=py37h2bbff1b_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rope=0.18.0=py_0
  - rsa=4.7=pyhd3eb1b0_1
  - rtree=0.9.4=py37h21ff451_1
  - scikit-image=0.15.0=py37ha925a31_0
  - scikit-learn=0.20.3=py37h343c172_0
  - scipy=1.2.1=py37h29ff71c_0
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py37haa95532_0
  - shapely=1.6.4=py37h222a598_0
  - simplejson=3.17.2=py37he774522_0
  - sip=4.19.8=py37h6538335_0
  - six=1.15.0=py37haa95532_0
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.3.0=pyhd3eb1b0_0
  - sphinx=3.4.3=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.4=pyhd3eb1b0_0
  - spyder=4.2.1=py37haa95532_1
  - spyder-kernels=1.10.1=py37haa95532_0
  - sqlalchemy=1.3.23=py37h2bbff1b_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.2=py37haa95532_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.2=py37h2bbff1b_1
  - typing_extensions=3.7.4.3=pyh06a4308_0
  - ujson=4.0.2=py37hd77b12b_0
  - uritemplate=3.0.1=py_0
  - urllib3=1.26.3=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=1.0.2=py37haa95532_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37_0
  - winpty=0.4.3=4
  - wrapt=1.11.2=py37he774522_0
  - xerces-c=3.2.3=ha925a31_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.30.0=py_0
  - yarl=1.5.1=py37he774522_0
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.5=h04227a9_0
prefix: C:\Users\z5025317\Anaconda3\envs\entrancesat

